import Header from "@/components/layout/header/Header";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import Footer from "@/components/layout/footer/Footer";
import SubFooter from "@/components/layout/footer/SubFooter";
import TopHeader from "@/components/layout/header/TopHeader";
// import PageWrapper from "@/components/layout/PageWrapper";
import ApolloProviders from "@/providers/ApolloProviders";
import ResponsiveNav from "@/components/layout/header/ResponsiveNav";

export const metadata = {
  title: "CollegeAdda",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
  manifest: "/manifest.webmanifest",
  "Content-Security-Policy": "upgrade-insecure-requests"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <ApolloProviders>
            <TopHeader />
            <Header />
            <ResponsiveNav />
            {/* <PageWrapper> */}
              <div className="mx-1 lg:mx-9">{children}</div>
            {/* </PageWrapper> */}
            <SubFooter />
            <Footer />
          </ApolloProviders>
        </body>
      </AuthProvider>
    </html>
  );
}
